language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "pip install ."
# command to run tests
script: nosetests

before_install:
  - pip install codecov
after_success:
  - codecov