language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - pip install -r tests/requirements.txt
  - "pip install ."
# command to run tests
script: nosetests  --rednose --with-cov
before_install:
  - pip install codecov
after_success:
  - codecov